name: CI
env:
    DEBUG: napi:*
    APP_NAME: files-rs
    MACOSX_DEPLOYMENT_TARGET: '10.13'
permissions:
    contents: write
    id-token: write
'on':
    push:
        branches:
            - master
        tags-ignore:
            - '**'
        paths-ignore:
            - '**/*.md'
            - '**/LICENSE'
            - '**/*.gitignore'
            - '**/*.editorconfig'
    pull_request: null
defaults:
    run:
        shell: bash
jobs:
    Build:
        strategy:
            fail-fast: false
            matrix:
                settings:
                  - host: macos-latest
                    target: x86_64-apple-darwin
                    architecture: x64
                    build: yarn build --target x86_64-apple-darwin
                  - host: windows-latest
                    target: x86_64-pc-windows-msvc
                    architecture: x64
                    build: yarn build --target x86_64-pc-windows-msvc
                  - host: windows-latest
                    target: i686-pc-windows-msvc
                    build: yarn build --target i686-pc-windows-msvc
                  - host: ubuntu-latest
                    target: x86_64-unknown-linux-gnu
                    architecture: x64
                    docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
                    build: |
                        yarn add bun -g
                        yarn build --target x86_64-unknown-linux-gnu
                  - host: ubuntu-latest
                    target: x86_64-unknown-linux-musl
                    architecture: x64
                    docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
                    build: |
                        yarn add bun -g
                        yarn build --target x86_64-unknown-linux-musl
                  - host: macos-latest
                    target: aarch64-apple-darwin
                    architecture: aarch64
                    build: yarn build --target aarch64-apple-darwin
                  - host: ubuntu-latest
                    target: aarch64-unknown-linux-gnu
                    architecture: aarch64
                    docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
                    build: |
                        yarn add bun -g
                        yarn build --target aarch64-unknown-linux-gnu
                  - host: ubuntu-latest
                    target: armv7-unknown-linux-gnueabihf
                    setup: |
                        sudo apt-get update
                        sudo apt-get install gcc-arm-linux-gnueabihf -y
                    build: yarn build --target armv7-unknown-linux-gnueabihf
                  - host: ubuntu-latest
                    target: armv7-unknown-linux-musleabihf
                    build: yarn build --target armv7-unknown-linux-musleabihf
                  - host: ubuntu-latest
                    target: aarch64-linux-android
                    architecture: aarch64
                    build: yarn build --target aarch64-linux-android
                  - host: ubuntu-latest
                    target: armv7-linux-androideabi
                    build: yarn build --target armv7-linux-androideabi
                  - host: ubuntu-latest
                    target: aarch64-unknown-linux-musl
                    architecture: aarch64
                    docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
                    build: |-
                        set -e &&
                        rustup target add aarch64-unknown-linux-musl &&
                        yarn build --target aarch64-unknown-linux-musl
                  - host: windows-latest
                    target: aarch64-pc-windows-msvc
                    architecture: aarch64
                    build: yarn build --target aarch64-pc-windows-msvc
                  - host: ubuntu-latest
                    target: riscv64gc-unknown-linux-gnu
                    setup: |
                        sudo apt-get update
                        sudo apt-get install gcc-riscv64-linux-gnu -y
                    build: yarn build --target riscv64gc-unknown-linux-gnu
                  - host: ubuntu-latest
                    target: x86_64-unknown-freebsd
                    architecture: x86_64
                    build: |
                        sudo pkg install -y -f node npm
                        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal --default-toolchain stable -y
                        . "$HOME/.cargo/env"
                        npm i
                        npm run build
                node: 
                    - 20
        name: Build ${{ matrix.settings.target }}-node@${{ matrix.node }}
        runs-on: ${{ matrix.settings.host }}
        env:
            DEBUG: napi:*
            RUSTUP_IO_THREADS: 1
        steps:
          - name: Checkout
            uses: actions/checkout@v4.2.1
          - name: Init
            if: ${{ matrix.settings.target == 'x86_64-unknown-freebsd' }}
            uses: cross-platform-actions/action@v0.25.0
            env:
                DEBUG: napi:*
                RUSTUP_IO_THREADS: 1
            with:
                shutdown_vm: false
                operating_system: freebsd
                architecture: x86-64
                version: '14.1'
                memory: 8G
                cpu_count: 4
                environment_variables: 'DEBUG RUSTUP_IO_THREADS'
                shell: bash
                run: ${{ matrix.settings.build }}
          - name: Install rust-toolchain
            if: ${{ matrix.settings.target != 'x86_64-unknown-freebsd' && !matrix.settings.docker }}
            uses: dtolnay/rust-toolchain@stable
            with:
                toolchain: stable
                targets: ${{ matrix.settings.target }}
          - name: Check Cargo
            if: ${{ matrix.settings.target != 'x86_64-unknown-freebsd' }}
            run: cargo -V
          - name: Cache cargo
            uses: actions/cache@v4
            with:
                path: |
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    .cargo-cache
                    target/
                key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}
          - name: Install node
            if: ${{ matrix.settings.target != 'x86_64-unknown-freebsd' && !matrix.settings.docker }}
            uses: actions/setup-node@v4
            with:
                node-version: ${{ matrix.node }}
          - name: Check node
            if: ${{ matrix.settings.target != 'x86_64-unknown-freebsd' }}
            run: |
                node -v
                npm -v
                node -p "process.platform"
                node -p "process.arch"
          - name: Check yarn
            if: ${{ matrix.settings.target != 'x86_64-unknown-freebsd' }}
            run: yarn -v
          - name: Install Bun
            if: ${{ matrix.settings.target != 'x86_64-unknown-freebsd' }}
            uses: oven-sh/setup-bun@v2.0.1
          - name: Check Bun
            if: ${{ matrix.settings.target != 'x86_64-unknown-freebsd' }}
            run: |
                bun -v
                bun -e "console.log(process.platform)"
                bun -e "console.log(process.arch)"
          - uses: goto-bus-stop/setup-zig@v2
            if: ${{ matrix.settings.target == 'armv7-unknown-linux-gnueabihf' || matrix.settings.target == 'armv7-unknown-linux-musleabihf' }}
            with:
                version: 0.13.0
          - name: Setup toolchain
            if: ${{ matrix.settings.target != 'x86_64-unknown-freebsd' && matrix.settings.setup }}
            run: ${{ matrix.settings.setup }}
          - name: Setup node x86
            if: ${{ matrix.settings.target == 'i686-pc-windows-msvc' }}
            run: yarn config set supportedArchitectures.cpu "ia32"
          - name: Install dependencies
            if: ${{ matrix.settings.target != 'x86_64-unknown-freebsd' }}
            run: bun i
          - name: Install node x86
            if: ${{ matrix.settings.target == 'i686-pc-windows-msvc' }}
            uses: actions/setup-node@v4
            with:
                node-version: ${{ matrix.node }}
                architecture: x86
          - name: Build in docker
            if: ${{ matrix.settings.docker }}
            uses: addnab/docker-run-action@v3
            with:
                image: ${{ matrix.settings.docker }}
                options: '--user 0:0 -v ${{ github.workspace }}/.cargo-cache/git/db:/usr/local/cargo/git/db -v ${{ github.workspace }}/.cargo/registry/cache:/usr/local/cargo/registry/cache -v ${{ github.workspace }}/.cargo/registry/index:/usr/local/cargo/registry/index -v ${{ github.workspace }}:/build -w /build'
                run: ${{ matrix.settings.build }}
          - name: Build
            if: ${{ matrix.settings.target != 'x86_64-unknown-freebsd' && !matrix.settings.docker }}
            run: ${{ matrix.settings.build }}
          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
                name: bindings-${{ matrix.settings.target }}
                path: "node/${{ env.APP_NAME }}.*.node"
                if-no-files-found: error
    Postbuild:
        name: Postbuild
        needs:
            - Build
        strategy:
            fail-fast: false
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4.2.1
          - name: Install node
            if: ${{ matrix.settings.target != 'x86_64-unknown-freebsd' }}
            uses: actions/setup-node@v4
          - name: Check node
            if: ${{ matrix.settings.target != 'x86_64-unknown-freebsd' }}
            run: |
                node -v
                npm -v
          - name: Install Bun
            if: ${{ matrix.settings.target != 'x86_64-unknown-freebsd' }}
            uses: oven-sh/setup-bun@v2.0.1
          - name: Check Bun
            if: ${{ matrix.settings.target != 'x86_64-unknown-freebsd' }}
            run: bun -v
          - name: Install dependencies
            run: bun i
          - name: Postbuild
            run: bun run _postbuild
          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
                name: bindings-dist
                path: "dist/**/*"
                if-no-files-found: error
          - name: Upload test_dist artifact
            uses: actions/upload-artifact@v4
            with:
                name: bindings-test-dist
                path: "test_dist/**/*"
                if-no-files-found: error
    Test:
        name: Test ${{ matrix.settings.target }}-${{ matrix.runtime }}
        needs:
            - Postbuild
        strategy:
            fail-fast: false
            matrix:
                settings:
                  - host: windows-latest
                    os: windows
                    version: latest
                    target: x86_64-pc-windows-msvc
                    lib: msvc
                    architecture: x64
                  - host: macos-latest
                    os: macos
                    version: latest
                    target: aarch64-apple-darwin
                    architecture: arm64
                  - host: macos-13
                    os: macos
                    version: '13'
                    target: x86_64-apple-darwin
                    architecture: x64
                  - host: ubuntu-latest
                    os: freebsd
                    version: '14.1'
                    target: x86_64-unknown-freebsd
                    architecture: x64
                    vm: freebsd:14.1
                  - host: ubuntu-latest
                    os: ubuntu
                    version: latest
                    target: x86_64-unknown-linux-gnu
                    lib: gnu
                    architecture: x64
                  - host: ubuntu-latest
                    os: alpine
                    version: latest
                    target: x86_64-unknown-linux-musl
                    lib: musl
                    architecture: x64
                    container: "node:20-alpine"
                    container_architecture: amd64
                  - host: ubuntu-latest
                    os: ubuntu
                    version: latest
                    target: aarch64-unknown-linux-gnu
                    lib: gnu
                    architecture: arm64
                    container: "ubuntu:latest"
                    container_architecture: "arm64"
                  - host: ubuntu-latest
                    os: alpine
                    version: latest
                    target: aarch64-unknown-linux-musl
                    lib: musl
                    architecture: arm64
                    container: "node:20-alpine"
                    container_architecture: arm64
                  - host: ubuntu-latest
                    os: debian
                    version: latest
                    target: armv7-unknown-linux-gnueabihf
                    lib: "gnu debian"
                    architecture: armv7
                    container: "node:20-bullseye-slim"
                    container_architecture: armv7   
                node:
                    - 20
                runtime:
                    - bun
                    - node
                    - deno
        runs-on: ${{ matrix.settings.host }}
        steps:
          - name: Checkout
            uses: actions/checkout@v4.2.1
          - name: Download node artifacts
            uses: actions/download-artifact@v4
            with:
                name: bindings-${{ matrix.settings.target }}
                path: 'node'
          - name: Download dist artifacts
            uses: actions/download-artifact@v4
            with:
                name: bindings-dist
                path: 'dist'
          - name: Download test_dist artifacts
            uses: actions/download-artifact@v4
            with:
                name: bindings-test-dist
                path: 'test_dist'
          - name: Init
            if: ${{ matrix.settings.container }}
            uses: sandervocke/setup-qemu-container@v1
            with:
                container: ${{ matrix.settings.container }}
                arch: ${{ matrix.settings.container_architecture }}
                podman_args: -v ${{ github.workspace }}:/build -w /build
          - name: Init
            if: ${{ matrix.settings.os == 'freebsd' }}
            uses: cross-platform-actions/action@v0.25.0
            with:
                shutdown_vm: false
                operating_system: ${{ matrix.settings.os }}
                architecture: ${{ matrix.settings.architecture }}
                version: ${{ matrix.settings.version }}
                memory: 8G
                cpu_count: 4
                shell: bash
                run: |
                    sudo pkg install -y -f node npm
                    uname -a
                    node -v
                    npm -v
                    node -p "process.platform"
                    node -p "process.arch"
                    npm i
                    bash ./scripts/tester.sh
          - name: Setup Shell Wrapper
            uses: sandervocke/setup-shell-wrapper@v1
          - name: Use regular shell
            if: ${{ !matrix.settings.container && !matrix.settings.vm }}
            shell: bash
            run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
          - name: Use container shell
            if: ${{ matrix.settings.container }}
            shell: bash
            run: echo "WRAP_SHELL=run-in-container.sh" >> $GITHUB_ENV
          - name: Use vm shell
            if: ${{ matrix.settings.vm }}
            shell: bash
            run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
          - name: Check os
            if: ${{ matrix.settings.os != 'macos' && !matrix.settings.vm && matrix.settings.os != 'alpine' }}
            shell: wrap-shell {0}
            run: |
                uname -a
                ldd --version
          - name: Check os
            if: ${{ matrix.settings.os == 'macos' && matrix.settings.os == 'alpine' }}
            shell: wrap-shell {0}
            run: |
                uname -a
          - name: Install node
            if: ${{ matrix.runtime == 'node' && !matrix.settings.vm && !matrix.settings.container }}
            uses: actions/setup-node@v4.0.4
            with:
                node-version: ${{ matrix.node }}
                architecture: ${{ matrix.settings.architecture }}
          - name: Install node
            if: ${{ matrix.runtime == 'node' && matrix.settings.container }}
            shell: wrap-shell {0}
            run: |
                sudo apt-get update
                sudo apt-get install nodejs
          - name: Check node
            if: ${{ matrix.runtime == 'node' && !matrix.settings.vm }}
            shell: wrap-shell {0}
            run: |
                node -v
                npm -v
                node -p "process.platform"
                node -p "process.arch"
          - name: Install Bun
            if: ${{ matrix.runtime == 'bun' && !matrix.settings.vm && !matrix.settings.container }}
            uses: oven-sh/setup-bun@v2.0.1
          - name: Install Bun
            if: ${{ matrix.runtime == 'bun' && matrix.settings.container }}
            shell: wrap-shell {0}
            run: |
                sudo apt-get update
                sudo apt-get install bun
          - name: Check Bun
            if: ${{ matrix.runtime == 'bun'  && !matrix.settings.vm }}
            shell: wrap-shell {0}
            run: |
                bun -v
                bun -e "console.log(process.platform)"
                bun -e "console.log(process.arch)"
          - name: Install Deno
            if: ${{ matrix.runtime == 'deno' && !matrix.settings.vm && !matrix.settings.container }}
            uses: denoland/setup-deno@v2
            with:
                deno-version: v2.x
          - name: Install Bun
            if: ${{ matrix.runtime == 'deno' && matrix.settings.container }}
            shell: wrap-shell {0}
            run: |
                sudo apt-get update
                sudo apt-get install deno
          - name: Check Deno
            if: ${{ matrix.runtime == 'deno' && !matrix.settings.vm }}
            shell: wrap-shell {0}
            run: deno --version
          - name: Install dependencies
            shell: wrap-shell {0}
            if: ${{ matrix.runtime == 'node' && !matrix.settings.vm }}
            run: npm i
          - name: Install dependencies
            shell: wrap-shell {0}
            if: ${{ matrix.runtime == 'bun' && !matrix.settings.vm }}
            run: bun i
          - name: Install dependencies
            shell: wrap-shell {0}
            if: ${{ matrix.runtime == 'deno' && !matrix.settings.vm }}
            run: deno i
          - name: Test bindings
            if: ${{ !matrix.settings.vm }}
            shell: wrap-shell {0}
            run: bash ./scripts/tester.sh
          - name: Test bindings
            if: ${{ false }}
            uses: addnab/docker-run-action@v3
            with:
                image: "node:${{ matrix.node }}-alpine"
                options: '--platform linux/amd64 --rm '
          - name: Test bindings
            if: ${{ false }}
            uses: addnab/docker-run-action@v3
            with:
                image: "node:20-bullseye-slim"
                options: '--platform linux/arm/v7 '
    Publish:
        name: Publish
        needs: 
            - Test
        strategy:
            fail-fast: false
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4.2.1