name: CI
permissions:
    contents: write
    id-token: write
'on':
    push:
        branches:
            - master
        tags-ignore:
            - '**'
        paths-ignore:
            - '**/*.md'
            - '**/LICENSE'
            - '**/*.gitignore'
            - '**/*.editorconfig'
    pull_request: null
defaults:
    run:
        shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: arm64v8/ubuntu
    steps:
      - name: Check architecture
        run: uname -m
