name: CI
permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**/LICENSE'
      - '**/*.gitignore'
      - '**/*.editorconfig'
  pull_request: null
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: arm64v8/ubuntu
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Check architecture
        run: uname -m
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y curl
          curl --version
      - name: Run your build or tests
        run: |
            uname -m
            ldd --version
