name: CI
permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**/LICENSE'
      - '**/*.gitignore'
      - '**/*.editorconfig'
  pull_request: null
defaults:
  run:
    shell: bash
jobs:
    container-test-job:
        runs-on: ubuntu-latest
        container:
            image: node:20-slim
        steps:
          - name: 
            run: |
                echo "--ls--"
                ls
                uname -m
                node -v
                npm -v
                node -p "process.platform"
                node -p "process.arch"
                ldd --version
