name: CI
permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**/LICENSE'
      - '**/*.gitignore'
      - '**/*.editorconfig'
  pull_request: null
defaults:
  run:
    shell: bash
jobs:
    container-test-job:
        runs-on: ubuntu-latest
        container:
            image: node:18
            env:
                NODE_ENV: development
            ports:
                - 80
            volumes:
                - my_docker_volume:/volume_mount
            options: --cpus 1
        steps:
          - name: Check for dockerenv file
            run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
